task:
  name: FreeBSD 14.1 MSRV
  env:
    VERSION: 1.81.0
  freebsd_instance:
    image: freebsd-14-1-release-amd64-ufs
  env:
    HOME: /tmp # cargo needs it
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo build
  test_script:
    - . $HOME/.cargo/env
    - cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index
